name: Unit Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Nodejs
        uses: actions/setup-node@v4

      - name: npm install
        run: npm i

      - name: Run Storybook
        run: |
          npm run storybook &
        env:
          CI: true

      - name: Wait for Storybook to be ready
        run: npx wait-on http://localhost:6006

      - name: Unit test
        run: |
          npx playwright install --with-deps chromium
          npm run test
